version: '3.2'

services:
  bpa-worker-py:
    image: rrortega/bpa-worker-py:latest
    environment:
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      PYTHONUNBUFFERED: 1
      RETHINKDB_HOST: "${RETHINKDB_HOST}"
      RETHINKDB_DATABASE: "${RETHINKDB_DATABASE}"
      RETHINKDB_PASSWORD: "${RETHINKDB_PASSWORD}"
    volumes:
      - ./crawler.py:/crawler.py
      - ./prpubsub.py:/prpubsub.py
      - ./main.py:/main.py
